swagger: '2.0'
info:
  description: Beta version of the DITAS Data Analytics REST API
  version: 0.0.8
  title: DITAS Data analytics
  contact:
    email: bogdan.despotov@cloudsigma.com
basePath: /data-analytics
tags:
  - name: Metrics
    description: Retrieval of metrics based on blueprint method
  - name: Resources
    description: Retrieval of cluster defined resources and current resource usage
schemes:
  - https
paths:
  '/meter/{operationID}/':
    get:
      tags:
        - Metrics
      description: Get metric value based on meter operation id, name, timestamp
      operationId: getmetrics
      produces:
        - application/json
        - application/xml
      parameters:
        - name: operationID
          in: path
          required: true
          description: Operation id based on deployment blueprint
          type: string
        - name: name
          in: query
          required: true
          description: Name of meter
          type: string
        - name: startTime
          in: query
          required: true
          description: Start timestamp of meter
          type: string
          format: date-time
        - name: endTime
          in: query
          required: true
          description: End timestamp of meter
          type: string
          format: date-time
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/metricRes'
        '400':
          description: Invalid data input
  '/resources/{infraId}/{nodeId}/':
    get:
      tags:
        - Resources
      summary: Outputs the CPU (cores) and memory (MB) capacity for nodeId and the capacity of the storage cluster (GB)
      operationId: resources
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: infraId
          description: The infrastructure name based on the blueprint
          required: true
          type: string
        - in: path
          name: nodeId
          description: The node name based on the blueprint
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Resources'
  '/resources/{infraId}/{nodeId}/usage/':
    get:
      tags:
        - Resources
      summary: Outputs the CPU percentage used by nodeId, the remaining free memory (MB) and the free space (GB) remaining on the storage cluster
      operationId: currentUsage
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: infraId
          description: The infrastructure name based on the blueprint
          required: true
          type: string
        - in: path
          name: nodeId
          description: The node name based on the blueprint
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Resources'
definitions:
  Resources:
    type: object
    properties:
      cpu:
        type: integer
      mem:
        type: integer
      storage:
        type: integer
  metricRes:
    type: object
    properties:
      operationID:
        type: string
      name:
        type: string
      value:
        type: integer
      unit:
        type: string
      timestamp:
        type: string
        format: date-time